<?php

use Illuminate\Database\Seeder;

class MobileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('mobiles')->insert([
            'name' => 'SAMSUNG GALAXY S20 G980 LTE 128GB 8GB RAM DUAL SIM CLOUD BLUE GARANZIA ITALIA', 
            'brand' => 'SAMSUNG', 
            'model' => 'S20', 
            'available' => '10', 
            'sold' => '10', 
            'price' => '789.99', 
            'discount' => '49', 
            'processor' => 'Octa Core', 
            'memory' => '8', 
            'storage' => '256', 
            'display' => '15', 
            'camera' => '12 Mp + 64 Mp + 12 Mp', 
            'featured' => 'yes', 
            'shipping' => 'free', 
            'condition' => 'New', 
            'color' => 'CLOUD BLUE', 
            'year' => '2020', 
            'os' => 'Android', 
            'image' => 's20.jpg',
            'user_id' => 1,
            'category' => "mobile",
            'sub_category' => "android",
        ]);

        DB::table('mobiles')->insert([
            'name' => 'Apple iPhone 11 Pro Max 256GB smartphone without contract', 
            'brand' => 'Apple', 
            'model' => 'Iphone 11 Pro Max - A2218', 
            'available' => '10', 
            'sold' => '10', 
            'price' => '1110.00', 
            'discount' => '49', 
            'processor' => 'Hexa Core', 
            'memory' => '4', 
            'storage' => '256', 
            'display' => '6.5 inches', 
            'camera' => '12.0 megapixels', 
            'featured' => 'yes', 
            'shipping' => 'free', 
            'condition' => 'New', 
            'color' => 'space gray, night green', 
            'year' => '2020', 
            'os' => 'IOS', 
            'image' => 'iphone11promax.jpg',
            'user_id' => 1,
            'category' => "mobile",
            'sub_category' => "apple",
        ]);

        DB::table('mobiles')->insert([
            'name' => 'LG V60 ThinQ 5G LMV600AM - 128GB - Classy Blue (Unlocked) AT&T,T-MOBILE', 
            'brand' => 'LG', 
            'model' => 'LM-V600AM', 
            'available' => '10', 
            'sold' => '10', 
            'price' => '899.00', 
            'discount' => '49', 
            'processor' => 'Octa Core', 
            'memory' => '8', 
            'storage' => '256', 
            'display' => '6.8 inches', 
            'camera' => '13.0 MP, 64.0 MP', 
            'featured' => 'yes', 
            'shipping' => 'free', 
            'condition' => 'New', 
            'color' => 'Blue', 
            'year' => '2020', 
            'os' => 'Android', 
            'image' => 'iphone11promax.jpg',
            'user_id' => 1,
            'category' => "mobile",
            'sub_category' => "android",
        ]);

        DB::table('mobiles')->insert([
            'name' => 'Samsung Galaxy Note 10+ Plus 5G SM-N976 256GB Aura Black Unlocked Smart Mobile', 
            'brand' => 'Samsung', 
            'model' => 'Note `10', 
            'available' => '10', 
            'sold' => '10', 
            'price' => '769.00', 
            'discount' => '49', 
            'processor' => 'Octa Core', 
            'memory' => '8', 
            'storage' => '256', 
            'display' => '6.8 Zoll', 
            'camera' => '16.0 Megapixel', 
            'featured' => 'yes', 
            'shipping' => 'free', 
            'condition' => 'New', 
            'color' => 'Black', 
            'year' => '2020', 
            'os' => 'Android', 
            'image' => 'note10plus1.jpg',
            'user_id' => 1,
            'category' => "mobile",
            'sub_category' => "android",
        ]);

        DB::table('mobiles')->insert([
            'name' => 'OnePlus 8 Pro 128GB Dual-Sim Onyx Black Smartphone Without Contract - New', 
            'brand' => 'OnePlus', 
            'model' => '8 Pro', 
            'available' => '10', 
            'sold' => '10', 
            'price' => '1054.00', 
            'discount' => '49', 
            'processor' => 'Octa Core', 
            'memory' => '8', 
            'storage' => '256', 
            'display' => '6.8 Zoll', 
            'camera' => '16.0 Megapixel', 
            'featured' => 'yes', 
            'shipping' => 'free', 
            'condition' => 'New', 
            'color' => 'Black', 
            'year' => '2020', 
            'os' => 'Android', 
            'image' => 'oneplus8pro1.jpg',
            'user_id' => 1,
            'category' => "mobile",
            'sub_category' => "android",
        ]);

        DB::table('mobiles')->insert([
            'name' => 'Apple iPhone 11 64GB Smartphone ohne Simlock verschiedene Farben WOW Angebot', 
            'brand' => 'Apple', 
            'model' => 'Iphone 11', 
            'available' => '10', 
            'sold' => '10', 
            'price' => '619', 
            'discount' => '49', 
            'processor' => 'Octa Core', 
            'memory' => '8', 
            'storage' => '256', 
            'display' => '6.8 Zoll', 
            'camera' => '16.0 Megapixel', 
            'featured' => 'yes', 
            'shipping' => 'free', 
            'condition' => 'New', 
            'color' => 'Black', 
            'year' => '2020', 
            'os' => 'Apple', 
            'image' => 'iphone11-1.jpg',
            'user_id' => 1,
            'category' => "mobile",
            'sub_category' => "apple",
        ]);

        DB::table('mobiles')->insert([
            'name' => 'Samsung Galaxy S10 Plus - SM-G975F/DS - S10+ 128GB Dual SIM Unlocked', 
            'brand' => 'Samsung', 
            'model' => 'S10 plus', 
            'available' => '10', 
            'sold' => '10', 
            'price' => '619', 
            'discount' => '49', 
            'processor' => 'Octa Core', 
            'memory' => '8', 
            'storage' => '256', 
            'display' => '6.8 Zoll', 
            'camera' => '16.0 Megapixel', 
            'featured' => 'yes', 
            'shipping' => 'free', 
            'condition' => 'New', 
            'color' => 'Black', 
            'year' => '2020', 
            'os' => 'Android', 
            'image' => 's10plus1.jpg',
            'user_id' => 1,
            'category' => "mobile",
            'sub_category' => "android",
        ]);

        DB::table('mobiles')->insert([
            'name' => 'Google Pixel 4 XL 64GB Black Smartphone Phone without Contract - Excellent condition', 
            'brand' => 'Google', 
            'model' => 'Pixel 4 XL', 
            'available' => '10', 
            'sold' => '10', 
            'price' => '691', 
            'discount' => '49', 
            'processor' => 'Octa Core', 
            'memory' => '8', 
            'storage' => '256', 
            'display' => '6.8 Zoll', 
            'camera' => '16.0 Megapixel', 
            'featured' => 'yes', 
            'shipping' => 'free', 
            'condition' => 'New', 
            'color' => 'Black', 
            'year' => '2020', 
            'os' => 'Android', 
            'image' => 'pixel1.png',
            'user_id' => 1,
            'category' => "mobile",
            'sub_category' => "android",
        ]);
    }
}
